[NAME]
functracer - list backtraces to allocations.

[DESCRIPTION]
\fBfunctracer\fR is a debugging tool. It gets backtraces of all allocations done in ARM/x86 processes. It works with optimized (-O2) code, where debugging symbols are available either in the application  binaries themselves, or in separate debug files.

[AUTHOR]
\fBFunctracer\fR has been developed by:

Anderson Lizardo <anderson.lizardo@indt.org.br>

Allan Bezerra <allan.bezerra@indt.org.br>

Bruna Moreira <bruna.moreira@indt.org.br>

Bruno Abinader <bruno.abinader@indt.org.br>

Ricardo Guimaraes <ricardo.guimaraes@indt.org.br>

Thiago Marcos P. Santos <thiago.santos@indt.org.br>

[COPYRIGHT]
Copyright (C) 2008 Nokia Corporation.

This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.

[SEE ALSO]
\fBfunctracer-postproc (1) \fR


