/*
 * This file is part of Functracer.
 * 
 * Copyright (C) 2008 by Nokia Corporation
 * 
 * Contact: Eero Tamminen <eero.tamminen@nokia.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#include <assert.h>
#include <libiberty.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>

#include "backtrace.h"
#include "config.h"
#include "debug.h"
#include "report.h"
#include "options.h"

static void rp_write_backtraces(struct process *proc)
{
	int bt_depth, j;
	char *backtrace[MAX_BT_DEPTH];
	struct rp_data *rd = proc->rp_data;

	bt_depth = bt_backtrace(proc->bt_data, backtrace, arguments.depth);

	debug(3, "rp_write_backtraces(pid=%d)", rd->pid);
	
	for (j = 0; j < bt_depth; j++) {
		fprintf(rd->fp, "   %s\n", backtrace[j]);
		free(backtrace[j]);
	}
}

void rp_alloc(struct process *proc, struct rp_alloc *ra)
{
	struct rp_data *rd = proc->rp_data;

	assert(rd != NULL);
	switch (ra->type) {
	case FN_FREE:
		debug(3, "rp_free(pid=%d, addr=0x%08x)", rd->pid, ra->addr);

		fprintf(rd->fp, "%d. free(0x%08x) = <void>\n", rd->rp_number,
			ra->addr);
		break;
	case FN_MALLOC:
		debug(3, "rp_malloc(pid=%d, addr=0x%08x, size=%d)", rd->pid,
		      ra->addr, ra->size);

		fprintf(rd->fp, "%d. malloc(%d) = 0x%08x\n", rd->rp_number,
			ra->size, ra->addr);
		break;
	case FN_CALLOC:
		debug(3, "rp_calloc(pid=%d, addr=0x%08x, nmemb=%d, size=%d)",
		      rd->pid, ra->addr, ra->nmemb, ra->size);

		fprintf(rd->fp, "%d. calloc(%d, %d) = 0x%08x\n", rd->rp_number,
			ra->nmemb, ra->size, ra->addr);
		break;
	case FN_MEMALIGN:
		debug(3, "rp_memalign(pid=%d, addr=0x%08x, boundary=%d, \
		      size=%d)", rd->pid, ra->addr, ra->boundary, ra->size);

		fprintf(rd->fp, "%d. memalign(%d, %d) = 0x%08x\n",
			rd->rp_number, ra->boundary, ra->size, ra->addr);
		break;
	case FN_REALLOC:
		debug(3, "rp_realloc(pid=%d, addr=0x%08x, addr_new=0x%08x, \
		      size=%d)", rd->pid, ra->addr, ra->addr_new, ra->size);

		fprintf(rd->fp, "%d. realloc(0x%08x, %d) = 0x%08x\n",
			rd->rp_number, ra->addr, ra->size, ra->addr_new);
		break;
	default:
		/* Should not happen */
		abort();
	}
	(rd->rp_number)++;
	if (ra->type != FN_FREE || arguments.enable_free_bkt)
		rp_write_backtraces(proc);

}

void rp_event(struct process *proc, const char *fmt, ...)
{
	struct rp_data *rd = proc->rp_data;
	va_list args;

	assert(rd != NULL);
	va_start(args, fmt);
	vfprintf(rd->fp, fmt, args);
	va_end(args);
}

static int rp_write_header(struct process *proc)
{
	struct rp_data *rd = proc->rp_data;
	char path[256];
	time_t start;

	if (arguments.save_to_file) {
		snprintf(path, sizeof(path), "%s/allocs-%d.%d.trace",
				arguments.path ? : getenv("HOME"), rd->pid,
				rd->step);

		rd->fp = fopen(path, "a");
		if (rd->fp == NULL) {
			error_exit("rp_init(): fopen");
			bt_finish(proc->bt_data);
			free(rd);
			proc->rp_data = rd = NULL;											
			return -1;
		}
	} else
		rd->fp = stdout;
	if (arguments.resolve_name)
		fprintf(rd->fp, "generated by %s, with resolved names, %s\n", PACKAGE_STRING, BUILD_ARCH);
	else
		fprintf(rd->fp, "generated by %s, %s\n", PACKAGE_STRING, BUILD_ARCH);
	time(&start);
	fprintf(rd->fp, "%s, PID %d, %s", name_from_pid(proc->pid), proc->pid, ctime(&start));

	return 0;
}

int rp_init(struct process *proc)
{
	struct rp_data *rd;

	debug(3, "pid=%d", proc->pid);

	if (proc->parent != NULL)
		rd = proc->parent->rp_data;
	else
		rd = proc->rp_data;
	if (rd == NULL) {
		rd = xcalloc(1, sizeof(struct rp_data));
		rd->pid = proc->pid;
	}
	proc->rp_data = rd;
	if (rd->refcnt++ == 0) {
		int ret = rp_write_header(proc);
		if (ret < 0)
			return ret;
	}
	proc->bt_data = bt_init(proc->pid);

	return 0;
}

void rp_finish(struct process *proc)
{
	struct rp_data *rd = proc->rp_data;

	assert(rd != NULL);
	bt_finish(proc->bt_data);
	assert(rd->refcnt > 0);
	if (--rd->refcnt == 0) {
		rd->step++;
		if (arguments.save_to_file)
			fclose(rd->fp);
	}
}
